# Generated by Django 4.0.4 on 2022-05-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('symbol', models.CharField(max_length=10)),
                ('date', models.DateTimeField()),
                ('to_currency_code', models.CharField(max_length=15)),
                ('to_country_region', models.CharField(max_length=30)),
                ('market_cap', models.DecimalField(decimal_places=4, max_digits=20)),
                ('circulating_supply', models.BigIntegerField(blank=True, null=True)),
                ('max_supply', models.BigIntegerField(blank=True, null=True)),
                ('value', models.DecimalField(decimal_places=4, max_digits=20)),
                ('source', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Cryptocurrency',
                'verbose_name_plural': 'Cryptocurrencies',
                'ordering': ['-market_cap'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('date', models.DateTimeField()),
                ('from_country_region', models.CharField(max_length=40)),
                ('to_country_region', models.CharField(max_length=40)),
                ('from_currency_code', models.CharField(max_length=15)),
                ('to_currency_code', models.CharField(max_length=15)),
                ('value', models.DecimalField(decimal_places=4, max_digits=20)),
                ('source', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['from_country_region'],
            },
        ),
    ]
