# Generated by Django 3.2.9 on 2021-11-09 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(max_length=7)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='conta.profile')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
                'ordering': ['-date'],
            },
        ),
    ]
